package com.papervest.notification.model;

public enum NotificationType {
	CONDITIONAL_ORDER_CREATED,
	CONDITIONAL_ORDER_TRIGGERED,
	CONDITIONAL_ORDER_FILLED,
	CONDITIONAL_ORDER_FAILED,
	CONDITIONAL_ORDER_CANCELLED,
	CONDITIONAL_ORDER_EXPIRED,
	EMAIL_VERIFIED,
	PASSWORD_CHANGED
}
