export const queryKeys = {
  home: ['home-market'] as const,
  stockDetail: (symbol: string) => ['stock-detail', symbol] as const,
  stockHistory: (symbol: string, range: string) => ['stock-history', symbol, range] as const,
  stockSearch: (query: string) => ['stock-search', query] as const,
  watchlist: ['watchlist'] as const,
  portfolio: ['portfolio'] as const,
  portfolioPerformanceRoot: ['portfolio-performance'] as const,
  portfolioPerformance: (range: string) => ['portfolio-performance', range] as const,
  cashFlows: ['cash-flows'] as const,
  tradeHistory: ['trade-history'] as const,
  orders: ['orders'] as const,
  order: (orderId: string) => ['order', orderId] as const,
  conditionalOrders: ['conditional-orders'] as const,
};
