export const queryKeys = {
  accountProfile: ['account-profile'] as const,
  adminAnalyticsOverview: (days: number) => ['admin-analytics-overview', days] as const,
  adminSupportUsers: (query: string) => ['admin-support-users', query] as const,
  adminSupportUser: (userId: string) => ['admin-support-user', userId] as const,
  home: ['home-market'] as const,
  notifications: ['notifications'] as const,
  portfolio: ['portfolio'] as const,
  portfolioHistoryRoot: ['portfolio-history'] as const,
  portfolioHistory: (range: string) => ['portfolio-history', range] as const,
  portfolioPerformance: (range: string) => ['portfolio-performance', range] as const,
  stockSearch: (query: string) => ['stock-search', query] as const,
  stockDetail: (symbol: string) => ['stock-detail', symbol] as const,
  stockHistory: (symbol: string, range: string) => ['stock-history', symbol, range] as const,
  watchlist: ['watchlist'] as const,
  tradeHistory: ['trade-history'] as const,
  orders: ['orders'] as const,
  order: (orderId: string) => ['order', orderId] as const,
  conditionalOrders: ['conditional-orders'] as const,
  conditionalOrder: (orderId: string) => ['conditional-order', orderId] as const,
};
