package com.papervest.conditionalorder.model;

public enum ConditionalOrderFailureCode {
	INSUFFICIENT_CASH,
	INSUFFICIENT_HOLDINGS,
	MARKET_DATA_UNAVAILABLE,
	ORDER_ALREADY_EXECUTED,
	ORDER_NOT_ACTIVE,
	ORDER_CANCELLED,
	ORDER_EXPIRED,
	PRICE_CONDITION_NOT_MET_ANYMORE,
	INTERNAL_ERROR
}
